### ISSUE TITLE
state designer core has missing dependencies

### ISSUE THREAD

**Issue by trafnar** [steveruizok/state-designer#27]
I tried to use `@state-designer/core` v2.0.3 (the latest as of this post) and found that two dependencies were missing, lodash and immer. I installed these myself and it worked.

I was confused because [this codesandbox example](https://codesandbox.io/s/g7ch1?file=/src/index.js) of state designer with vanilla JS worked, but when I updated the state designer dependency to 2.0.3, it shows the missing dependency error, you can see that reproduced in [this sandbox](https://codesandbox.io/s/cocky-frost-t5xx0).

Just wanted to let you know, I'm excited to try using state designer with [Imba](https://imba.io), its working nicely so far.

**Comment by steveruizok** [comment]
Should be fixed now!
